# Generated by Django 3.0.8 on 2020-07-27 05:08

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('remote', models.BooleanField(default=False)),
                ('company_logo', models.URLField()),
                ('No_of_Assignments', models.IntegerField(null=True)),
                ('if_updated', models.BooleanField(default=True)),
                ('No_of_Openings', models.IntegerField(null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=5000), blank=True, size=None)),
                ('Description', models.TextField(default='')),
                ('location', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=5000), blank=True, size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.URLField()),
                ('tech_stack', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
