# Generated by Django 3.0.7 on 2020-06-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgImage', models.TextField()),
                ('companyName', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('scale', models.CharField(max_length=100)),
                ('jobs', models.CharField(max_length=100)),
                ('skill1', models.CharField(max_length=50)),
                ('skill2', models.CharField(max_length=50)),
                ('skill3', models.CharField(max_length=50)),
                ('skill4', models.CharField(max_length=50)),
                ('skill5', models.CharField(max_length=50)),
            ],
        ),
    ]
