# Generated by Django 3.0.7 on 2020-07-05 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgImage', models.TextField()),
                ('companyName', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('assignment', models.IntegerField()),
                ('jobs', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=50)),
                ('companie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cskill', to='index.companies')),
            ],
        ),
    ]
