# Generated by Django 3.0.7 on 2020-06-28 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companies', models.CharField(max_length=50)),
                ('companie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.companies')),
            ],
        ),
    ]
