# Generated by Django 3.0.7 on 2020-06-28 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='companies',
            new_name='skills',
        ),
    ]
