# Generated by Django 3.0.7 on 2020-06-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200628_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='skill1',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='skill2',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='skill3',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='skill4',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='skill5',
        ),
    ]
