# Generated by Django 3.0.7 on 2020-07-08 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_company_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='NoofAssignments',
            new_name='No_of_Assignments',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='NoofOpenings',
            new_name='No_of_Openings',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='Logo',
            new_name='company_logo',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='Company',
            new_name='company_name',
        ),
    ]
