# Generated by Django 3.0.7 on 2020-07-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='remote',
            field=models.BooleanField(default=False),
        ),
    ]
