# Generated by Django 3.0.7 on 2020-06-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20200628_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='scale',
        ),
        migrations.AddField(
            model_name='companies',
            name='assignment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
