# Generated by Django 3.0.8 on 2020-07-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_assessment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='c_type',
            new_name='job_type',
        ),
    ]
